version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-network
  
  node:
    image: node:15
    working_dir: /usr/src/app
    container_name: node
    tty: true
    volumes:
      - ./node/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    networks:
      - desafio-network
    command: >
      sh -c "npm install &&
             node index.js"
  
  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - desafio-network
    depends_on:
      - node

networks:
  desafio-network:
    driver: bridge